name: Build Docs
on: 
  workflow_dispatch:
  push:
    branches: 
      - master
    tags:
      - '*'
jobs:
  build_docs:
    runs-on: [self-hosted, windows]
    steps:
      - name: Cleanup working directory
        working-directory: ${{ github.workspace }}
        run: del *.* /Q /S
        shell: cmd
      - name: Checkout doc repository repository
        uses: actions/checkout@v1
        with:
          ref: 'master'
      - name: Clone snippet directory
        uses: sudosubin/git-clone-action@v1.0.1
        with:
          repository: qdr/HiseSnippetDB
          path: '/hise_snippets'
      - name: Download Assets from release
        uses: robinraju/release-downloader@v1.11
        with:
          repository: qdr/HiseSnippetDB
          latest: true
          fileName: 'Assets.zip'
          out-file-path: './hise_snippets/Assets'
          extract: true
      - name: Run HISE CI build to create docs
        run: build.bat
        shell: cmd
      - name: Push HTML build
        uses: cpina/github-action-push-to-another-repository@v1.7.2
        with:
          source-directory: /html_build
          destination-github-username: christophhart
          destination-repository-name: hise_doc_html
          user-email: christoph-hart@gmx.de
          commit-message: 'push from build server'
      - name: Upload Cached files
        uses: astertom/nexus-upload-artifact@v1
        with:
          directory: /cached
          pattern: '*'
